In [2]:
import numpy as np
from read_vis_class import Read_File
from astropy.io import fits
from astropy.io import ascii
from astropy.cosmology import FlatLambdaCDM

In [19]:
inf = ascii.read('/Users/connor_auge/Research/Disertation/AHA_SED_paper1_materials/Tables/datafileA1.txt')

In [3]:
field = np.asarray(inf['Field'])
xid = np.asarray(inf['xID'])[field == 'Stripe82X']
rah = np.asarray(inf['RAh'])[field == 'Stripe82X']
ram = np.asarray(inf['RAm'])[field == 'Stripe82X']
ras = np.asarray(inf['RAs'])[field == 'Stripe82X'] 
de = np.asarray(inf['DE-'])[field == 'Stripe82X']
ded = np.asarray(inf['DEd'])[field == 'Stripe82X'] 
dem = np.asarray(inf['DEm'])[field == 'Stripe82X']
des = np.asarray(inf['DEs'])[field == 'Stripe82X']
z = np.asarray(inf['zspec'])[field == 'Stripe82X']

In [26]:
field = np.asarray(inf['Field'])
xid = np.asarray(inf['xID'])[field == 'COSMOS']
phot_id = np.asarray(inf['photID'])[field == 'COSMOS']
rah = np.asarray(inf['RAh'])[field == 'COSMOS']
ram = np.asarray(inf['RAm'])[field == 'COSMOS']
ras = np.asarray(inf['RAs'])[field == 'COSMOS'] 
de = np.asarray(inf['DE-'])[field == 'COSMOS']
ded = np.asarray(inf['DEd'])[field == 'COSMOS'] 
dem = np.asarray(inf['DEm'])[field == 'COSMOS']
des = np.asarray(inf['DEs'])[field == 'COSMOS']
z = np.asarray(inf['zspec'])[field == 'COSMOS']

In [27]:
print(f'{rah[0]}:{ram[0]}:{ras[0]}')
print(f'{de[0]}{ded[0]}:{dem[0]}:{des[0]}')


9:59:45.0307428
+1:28:28.6445203


In [28]:
print(f'{rah[210]}:{ram[210]}:{ras[210]}')
print(f'{de[210]}{ded[210]}:{dem[210]}:{des[210]}')

9:59:46.77120499
+2:4:41.56135932


In [29]:
def dist_to_arcsec(z):
    cosmo = FlatLambdaCDM(H0=70, Om0=0.29, Tcmb0=2.725)
    dl = cosmo.luminosity_distance(z).value  # Distance in Mpc
    dl_kpc = dl*1000

    theta = 70/dl_kpc*206265

    for i in range(len(theta)):
        if theta[i] < 5:
            theta[i] = 5
    
    return np.asarray(theta,dtype=int)

arcsec = dist_to_arcsec(z)

In [17]:
outf = open('/Users/connor_auge/Research/Disertation/morphology/visual/S82X/HSC_coord_list_g2.txt','w')
outf.writelines('#? rerun    filter    ra    dec    sw    sh    nodata    name\n')
for i in range(len(xid)):
    outf.writelines('%s    %s    %s    %s    %s    %s    %s    %s\n' % ('pdr3_wide','HSC-G',str(rah[i])+':'+str(ram[i])+':'+str(ras[i]),
                                                                        str(de[i])+str(ded[i])+':'+str(dem[i])+':'+str(des[i]), 
                                                                        f'{arcsec[i]}arcsec', f'{arcsec[i]}arcsec', True, str(xid[i])))
                                                                        # '5asec','5asec','True',str(xid[i])))
outf.close()

In [31]:
outf = open('/Users/connor_auge/Research/Disertation/morphology/visual/COSMOS/HSC_coord_list_r.txt','w')
outf.writelines('#? rerun    filter    ra    dec    sw    sh    nodata    name\n')
for i in range(len(xid)):
    outf.writelines('%s    %s    %s    %s    %s    %s    %s    %s\n' % ('pdr3_wide','HSC-R',str(rah[i])+':'+str(ram[i])+':'+str(ras[i]),
                                                                        str(de[i])+str(ded[i])+':'+str(dem[i])+':'+str(des[i]), 
                                                                        f'{arcsec[i]}arcsec', f'{arcsec[i]}arcsec', True, str(phot_id[i])))
                                                                        # '5asec','5asec','True',str(xid[i])))
outf.close()

In [15]:
str(rah[0])+':'+str(ram[0])+':'+str(ras[0])

'0:56:27.48046875'

In [16]:
str(de[0])+str(ded[0])+':'+str(dem[0])+':'+str(des[0])

'-0:21:11.48852348'

In [2]:
inf = Read_File('Auge_COSMOS_classifications_read.xlsx')
inf.open(type='xlsx')


In [3]:
cols = inf.columns()
data = inf.data()
notes = inf.notes()

In [4]:
cols

array(['ID', 'Disk', 'Disk-Spheroid', 'Spheroid', 'Irregular', 'PS',
       'Unclassifiable', 'Blank', 'Merger_flag', 'TF_flag', 'PS_flag'],
      dtype=object)

In [5]:
print(len(cols))
print(len(data[0]))

11
11


In [8]:
data

array([[123228.0, nan, nan, ..., nan, nan, nan],
       [128954.0, nan, nan, ..., nan, nan, nan],
       [150058.0, nan, nan, ..., nan, nan, nan],
       ...,
       [1046875.0, nan, nan, ..., nan, nan, nan],
       [1047454.0, nan, nan, ..., nan, nan, nan],
       [1057210.0, nan, nan, ..., nan, nan, nan]], dtype=object)

In [9]:
data[0]

array([123228.0, nan, nan, nan, nan, nan, nan, 'x', nan, nan, nan],
      dtype=object)

In [2]:
a = np.arange(10,15,1)
b = np.arange(0,5,1)
c = np.array([np.arange(0,5,1),np.arange(20,25,1),np.arange(50,55,1),np.arange(60,65,1),np.arange(80,85,1)])
test_dict = dict.fromkeys(a)

In [3]:
for i in range(len(a)):
    # if test_dict[a[i]] == None:
    test_dict[a[i]] = c[i]
    # else:
    #     test_dict[a[i]].append(b[i])

In [4]:
test_dict

{10: array([0, 1, 2, 3, 4]),
 11: array([20, 21, 22, 23, 24]),
 12: array([50, 51, 52, 53, 54]),
 13: array([60, 61, 62, 63, 64]),
 14: array([80, 81, 82, 83, 84])}

In [15]:
list(test_dict.keys())

[10, 11, 12, 13, 14]

In [17]:
len(test_dict.values())

5

In [18]:
test_dict.values()

dict_values([array([0, 1, 2, 3, 4]), array([20, 21, 22, 23, 24]), array([50, 51, 52, 53, 54]), array([60, 61, 62, 63, 64]), array([80, 81, 82, 83, 84])])

In [3]:
a = np.array([1,2,3,4,0])
b = np.array([1,1,1,1,1])

c = np.array([a,b])

In [4]:
c

array([[1, 2, 3, 4, 0],
       [1, 1, 1, 1, 1]])

In [5]:
np.concatenate(c)

array([1, 2, 3, 4, 0, 1, 1, 1, 1, 1])

In [7]:
np.sum(c,axis=0)

array([2, 3, 4, 5, 1])

In [15]:
a = np.asarray(['abc_123','abc_00123'])

a[1][4:]

'00123'

array(['abc_123', 'abc_00123'], dtype='<U9')